"""Measure every catalog column and write what the SQL model should know about it.

    python -m catalog.profiler              # every domain
    python -m catalog.profiler listings     # one domain

For each column: the share of rows that are filled; for a text column with few distinct
values, all of them; for a categorical column with more, the most common ones; and for a
date column, the span that holds almost all of its rows.
Large tables are sampled. Read-only. The output is one YAML file per domain under
catalog/profiles/, which `domain_prompt` merges into the schema context.
"""

from __future__ import annotations

import sys
from datetime import date

import yaml
from psycopg import sql
from psycopg.rows import dict_row

from catalog.registry import PROFILES_DIR, list_domains, load_domain
from common.db import close_pools, get_pool, warehouse_conninfo
from common.logger import get_logger

logger = get_logger("catalog.profiler")

# A text column with at most this many distinct values is listed in full.
MAX_LISTED_VALUES = 25
# Up to this many distinct values, a column is categorical and its most common values are listed.
MAX_CATEGORICAL_VALUES = 300
MAX_COMMON_VALUES_LISTED = 15
MAX_VALUE_LENGTH = 80
# Tables with more rows than this are sampled down to roughly this many.
SAMPLE_TARGET_ROWS = 200_000
PROFILE_TIMEOUT_MS = 120_000
_TEXT_TYPES = ("char", "text")
_DATE_TYPES = ("date", "timestamp")
# A date span drops this share of rows at each end, so a stray 1900 or 2109 does not stretch it.
DATE_SPAN_TAIL_SHARE = 0.005


def profile_domain(domain_id: str, runner) -> dict:
    """{qualified table name: {column: {filled, values?}}} for one domain."""
    profiles: dict = {}
    for table in load_domain(domain_id).get("tables") or []:
        qualified = table.get("qualified_name")
        columns = [column for column in table.get("columns") or [] if column.get("name")]
        if not qualified or "." not in qualified or not columns:
            continue
        try:
            profiles[qualified] = _profile_table(qualified, columns, runner)
        except Exception as exc:
            logger.warning(
                "profile.table_failed",
                extra={"extra_data": {"table": qualified, "error": str(exc)[:200]}},
            )
    return profiles


def write_profile(domain_id: str, profiles: dict) -> None:
    PROFILES_DIR.mkdir(exist_ok=True)
    header = f"# Generated by `python -m catalog.profiler {domain_id}` on {date.today().isoformat()}. Do not edit.\n"
    body = yaml.safe_dump(profiles, sort_keys=False, allow_unicode=True, width=100)
    (PROFILES_DIR / f"{domain_id}.yaml").write_text(header + body, encoding="utf-8")


def _profile_table(qualified: str, columns: list[dict], runner) -> dict:
    schema, name = qualified.split(".", 1)
    source = _sampled_source(schema, name, runner)
    counts = runner(
        sql.SQL("SELECT count(*) AS total, {counts} FROM {source}").format(
            counts=sql.SQL(", ").join(
                sql.SQL("count({}) AS {}").format(sql.Identifier(column["name"]), sql.Identifier(f"c{index}"))
                for index, column in enumerate(columns)
            ),
            source=source,
        )
    )[0]
    total = int(counts["total"] or 0)
    profile: dict = {}
    for index, column in enumerate(columns):
        filled = int(counts[f"c{index}"] or 0) / total if total else 0.0
        facts: dict = {"filled": round(filled, 3)}
        if filled and _is_text(column):
            facts.update(_value_facts(column["name"], source, runner))
        elif filled and _is_date(column):
            facts.update(_date_facts(column["name"], source, runner))
        profile[column["name"]] = facts
    return profile


def _sampled_source(schema: str, name: str, runner) -> sql.Composable:
    table = sql.Identifier(schema, name)
    estimate = runner(
        sql.SQL("SELECT GREATEST(reltuples, 0)::bigint AS estimate FROM pg_class WHERE oid = {}::regclass").format(
            sql.Literal(f"{schema}.{name}")
        )
    )[0]["estimate"]
    if not estimate or estimate <= SAMPLE_TARGET_ROWS:
        return table
    percent = max(0.01, round(100 * SAMPLE_TARGET_ROWS / estimate, 3))
    return sql.SQL("{} TABLESAMPLE SYSTEM ({})").format(table, sql.Literal(percent))


def _value_facts(column: str, source: sql.Composable, runner) -> dict:
    """`values` when the column has few distinct values, `common_values` when it is categorical."""
    rows = runner(
        sql.SQL(
            "SELECT {col}::text AS value, count(*) AS n FROM {source} WHERE {col} IS NOT NULL "
            "GROUP BY 1 ORDER BY 2 DESC LIMIT {limit}"
        ).format(col=sql.Identifier(column), source=source, limit=sql.Literal(MAX_CATEGORICAL_VALUES + 1))
    )
    values = [str(row["value"]) for row in rows]
    if not values or len(values) > MAX_CATEGORICAL_VALUES or any(len(v) > MAX_VALUE_LENGTH for v in values):
        return {}
    if len(values) <= MAX_LISTED_VALUES:
        return {"values": values}
    return {"common_values": values[:MAX_COMMON_VALUES_LISTED]}


def _date_facts(column: str, source: sql.Composable, runner) -> dict:
    """`covers`: the first and last date once the outlying rows at each end are dropped."""
    row = runner(
        sql.SQL(
            "SELECT percentile_disc({low}) WITHIN GROUP (ORDER BY {col})::date AS first, "
            "percentile_disc({high}) WITHIN GROUP (ORDER BY {col})::date AS last "
            "FROM {source} WHERE {col} IS NOT NULL"
        ).format(
            col=sql.Identifier(column),
            source=source,
            low=sql.Literal(DATE_SPAN_TAIL_SHARE),
            high=sql.Literal(1 - DATE_SPAN_TAIL_SHARE),
        )
    )[0]
    if not row["first"] or not row["last"]:
        return {}
    return {"covers": f"{row['first'].isoformat()} to {row['last'].isoformat()}"}


def _is_date(column: dict) -> bool:
    kind = str(column.get("type") or "").lower()
    return kind.startswith(_DATE_TYPES)


def _is_text(column: dict) -> bool:
    kind = str(column.get("type") or "").lower()
    return any(marker in kind for marker in _TEXT_TYPES)


def _create_readonly_warehouse_runner():
    pool = get_pool(
        "warehouse_profiler",
        warehouse_conninfo(),
        max_size=1,
        connect_kwargs={"row_factory": dict_row},
    )

    def run(statement: sql.Composable) -> list[dict]:
        with pool.connection() as connection, connection.transaction():
            connection.execute("SET LOCAL transaction_read_only = on")
            connection.execute(sql.SQL("SET LOCAL statement_timeout = {}").format(sql.Literal(PROFILE_TIMEOUT_MS)))
            return connection.execute(statement).fetchall()

    return run


def main(domain_ids: list[str]) -> None:
    runner = _create_readonly_warehouse_runner()
    try:
        for domain_id in domain_ids or [domain["id"] for domain in list_domains()]:
            profiles = profile_domain(domain_id, runner)
            write_profile(domain_id, profiles)
            print(f"{domain_id}: {len(profiles)} tables profiled")
    finally:
        close_pools()


if __name__ == "__main__":
    main(sys.argv[1:])
