from enum import Enum


class APIErrorSubCode(str, Enum):
    """Detailed error subcodes for specific failure reasons."""

    NOT_FOUND = "NOT_FOUND"
    ALREADY_EXISTS = "ALREADY_EXISTS"
    BAD_DATA = "BAD_DATA"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"

    INVALID_TOKEN = "INVALID_TOKEN"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"

    RATE_LIMITED = "RATE_LIMITED"

    AI_GENERATION_FAILED = "AI_GENERATION_FAILED"
    SQL_REJECTED = "SQL_REJECTED"
    SQL_FAILED = "SQL_FAILED"

    INTERNAL_ERROR = "INTERNAL_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"
